import pandas as pd
from pymongo import MongoClient
from dotenv import load_dotenv
import os

load_dotenv()

# Connect to MongoDB
client = MongoClient(os.getenv("MONGODB_URL"))
db = client[os.getenv("DATABASE_NAME")]

print("=" * 60)
print("LAPTOP DATABASE SEEDING")
print("=" * 60)

# Read CSV
print("\n[1] Reading CSV file...")
df = pd.read_csv('laptop_data2.csv')
print(f"✅ Found {len(df)} laptops in CSV")

# Convert to dict
laptops = df.to_dict('records')

# Clean and prepare data
print("\n[2] Cleaning and preparing data...")
for i, laptop in enumerate(laptops):
    # Convert price to int
    try:
        laptop['price'] = int(str(laptop['Price']).replace(',', ''))
        del laptop['Price']
    except:
        print(f"⚠️ Warning: Could not parse price for laptop {i+1}")
        laptop['price'] = 0
    
    # Rename fields to lowercase with underscores
    laptop['brand'] = laptop.pop('Brand', 'Unknown')
    laptop['model_name'] = laptop.pop('Model Name', 'Unknown')
    laptop['core'] = laptop.pop('Core', 'Unknown')
    laptop['cpu_manufacturer'] = laptop.pop('CPU Manufacturer', 'Unknown')
    laptop['clock_speed'] = laptop.pop('Clock Speed', 'Unknown')
    laptop['ram_size'] = laptop.pop('RAM Size', 'Unknown')
    laptop['storage_type'] = laptop.pop('Storage Type', 'Unknown')
    laptop['display_type'] = laptop.pop('Display Type', 'Unknown')
    laptop['display_size'] = laptop.pop('Display Size', 'Unknown')
    laptop['graphics_processor'] = laptop.pop('Graphics Processor', 'Unknown')
    laptop['screen_resolution'] = laptop.pop('Screen Resolution', 'Unknown')
    laptop['os'] = laptop.pop('OS', 'Unknown')
    laptop['laptop_weight'] = laptop.pop('Laptop Weight', 'Unknown')
    laptop['special_features'] = laptop.pop('Special Features', 'Unknown')
    laptop['warranty'] = laptop.pop('Warranty', 'Unknown')
    laptop['average_battery_life'] = laptop.pop('Average Battery Life', 'Unknown')
    laptop['description'] = laptop.pop('Description', '')
    
    # DO NOT add laptop_feature here - it will be generated by Groq later

print(f"✅ Data cleaned successfully")

# Clear existing data
print("\n[3] Clearing existing data from database...")
result = db.laptops.delete_many({})
print(f"✅ Deleted {result.deleted_count} existing laptops")

# Insert data WITHOUT laptop_feature
print("\n[4] Inserting new laptop data...")
result = db.laptops.insert_many(laptops)
print(f"✅ Inserted {len(result.inserted_ids)} laptops into MongoDB")

print("\n" + "=" * 60)
print("SEEDING COMPLETE!")
print("=" * 60)
print("\n⚠️ IMPORTANT: Laptop features not generated yet!")
print("Next step: Run 'python generate_laptop_features.py' to generate features using Groq AI")
print("=" * 60)